<script id="tailwind-config">
tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            colors: {
                "on-tertiary-fixed": "#001f27",
                "on-error-container": "#93000a",
                "on-primary-fixed": "#001848",
                "tertiary-container": "#006477",
                "on-primary-fixed-variant": "#0040a2",
                "on-error": "#ffffff",
                "secondary-container": "#82f9be",
                "secondary-fixed": "#82f9be",
                "tertiary-fixed-dim": "#48d7f9",
                "primary-fixed-dim": "#b2c5ff",
                "background": "#f9f9ff",
                "on-secondary-container": "#00734c",
                "surface-tint": "#0c56d0",
                "primary-container": "#0052cc",
                "on-primary": "#ffffff",
                "secondary": "#006c47",
                "surface-bright": "#f9f9ff",
                "tertiary-fixed": "#afecff",
                "inverse-surface": "#20314b",
                "on-secondary-fixed-variant": "#005235",
                "error-container": "#ffdad6",
                "surface-container-lowest": "#ffffff",
                "on-surface-variant": "#434654",
                "on-tertiary-fixed-variant": "#004e5d",
                "on-tertiary": "#ffffff",
                "primary": "#003d9b",
                "secondary-fixed-dim": "#65dca4",
                "surface-container-high": "#dfe8ff",
                "on-surface": "#091c35",
                "on-background": "#091c35",
                "inverse-on-surface": "#ecf0ff",
                "surface": "#f9f9ff",
                "on-tertiary-container": "#76e2ff",
                "inverse-primary": "#b2c5ff",
                "surface-container": "#e7eeff",
                "tertiary": "#004b59",
                "on-secondary-fixed": "#002113",
                "outline-variant": "#c3c6d6",
                "error": "#ba1a1a",
                "surface-variant": "#d6e3ff",
                "surface-dim": "#cadbfc",
                "outline": "#737685",
                "surface-container-low": "#f0f3ff",
                "primary-fixed": "#dae2ff",
                "surface-container-highest": "#d6e3ff",
                "on-primary-container": "#c4d2ff",
                "on-secondary": "#ffffff"
            },
            fontFamily: {
                "headline": ["Manrope", "sans-serif"],
                "body": ["Inter", "sans-serif"],
                "label": ["Inter", "sans-serif"],
                "manrope": ["Manrope", "sans-serif"]
            },
            borderRadius: { "DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem" },
        },
    },
}
</script>
